apiVersion: v1
kind: LimitRange
metadata:
  creationTimestamp: null
  labels:
    run: cpu-limit-range
  name: cpu-limit-range
spec:
  limits:
    - default:
        cpu: 0.5 #limit
      defaultRequest:
        cpu: 0.3 #Request
      max:
        cpu: 1
      min:
        cpu: 0.1
      type: Container

