apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod3
  name: pod3
spec:
  containers:
  - image: nginx
    name: pod3
    envFrom:
    - secretRef:
        name: ext-service-secret
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
