apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: cronjob-demo
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: cronjob-demo
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: busybox
            name: cronjob-demo
            resources: {}
          restartPolicy: OnFailure
  schedule: '* * * * *'
status: {}
