apiVersion: v1
kind: LimitRange
metadata:
  creationTimestamp: null
  labels:
    run: memory-limit-range
  name: memory-limit-range
spec:
 limits:
  - default:
      memory: 300Mi #limit
    defaultRequest:
      memory: 100Mi #request
    min:
      memory: 100Mi
    max:
      memory: 500Mi
    type: Container
