apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod2
  name: pod2
spec:
  containers:
  - image: nginx
    name: pod2
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          key: username
          name: secret2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
